openapi: 3.0.1
info:
  title: UrlTapper Rest Api
  description: Tapping the length of the url and returning unique shortened url
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: UrlTapper Rest Api
    description: Tapping the length of the url and returning unique shortened url
paths:
  /v1/tapurl:
    post:
      tags:
        - UrlTapper Rest Api
      description: shorten the given long url
      operationId: tapUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlTapRequest'
        required: true
      responses:
        '200':
          description: if the long url successfully generated the short url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlTapResponse'
        '400':
          description: if the long url not found on the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlTapResponse'
  /v1/geturl:
    get:
      tags:
        - UrlTapper Rest Api
      description: retrieve the long url
      operationId: getUrl
      parameters:
        - name: shortUrl
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: if the short url fetched and redirection happened successfully
          content:
            '*/*':
              schema:
                type: string
        '400':
          description: if the shore url not found on the request
          content:
            '*/*':
              schema:
                type: string
        '404':
          description: if the short url not found on the database
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    UrlTapRequest:
      type: object
      properties:
        longUrl:
          type: string
          description: long link of the url
    UrlTapResponse:
      type: object
      properties:
        shortUrl:
          type: string
          description: hashed short link of the url
