openapi: 3.0.1
info:
  title: UrlTapper Rest Api
  description: Tapping the length of the url and returning unique shortened url.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: UrlTapper Rest Api Controller
    description: This Controller provides tapurl and geturl API functions.
paths:
  /v1/tapurl:
    post:
      tags:
        - tapUrl
      description: shorten the given long url
      operationId: tapUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlTapRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlTapResponse'
  /v1/geturl:
    post:
      tags:
        - getUrl
      description: retrieve the long url
      operationId: getUrl
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlGetRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlGetResponse'
components:
  schemas:
    UrlTapRequest:
      type: object
      properties:
        longUrl:
          type: string
          description: long link of the url
    UrlTapResponse:
      type: object
      properties:
        shortUrl:
          type: string
          description: hashed short link of the url
    UrlGetRequest:
      type: object
      properties:
        shortUrl:
          type: string
          description: hashed short link of the url
    UrlGetResponse:
      type: object
      properties:
        longUrl:
          type: string
          description: long link of the url
